### ISSUE TITLE
Huge CPU usage since iOS 16.1

### ISSUE THREAD

**Issue by Reactor13** [uakihir0/UIPiPView#17]
Huge CPU usage since iOS 16.1

Hi. Our users point that since iOS 16.1 our app with PiP drain battery very fast.

We had tested it. So. If PiP disabled then our app use about 2-5% CPU time. As soon as the PiP is turned on, the usage instantly grows to 110% - 130%.

We have changed the library code in such a way as to exclude any influence of our code. There was no content rendering for the test. Just a black window. And yet the load is the same 110% - 130%.

Can you confirm that you are experiencing the same issue? Is it library specific or is it a system bug. If this is a system bug, then let's create a defect in Apple Bug Tracker. Because iOS 16.2 has already been released, but the problem has not been solved.

**Comment by kleruk88** [comment]
we have the same problems

**Comment by Reactor13** [comment]
> we have the same problems

I have been tested it on latest XCode 14.2 on latest iOS 16.2. There is no result, still 110-130% CPU usage...

**Comment by kleruk88** [comment]
for example
**PiP - ON**
<img width="827" alt="on background" src="https://user-images.githubusercontent.com/120883548/208370354-55f576b2-c1f2-441c-b66a-03bfe634aa29.png">
**PiP - Off**
<img width="836" alt="off background" src="https://user-images.githubusercontent.com/120883548/208370376-d9fedfa2-8c2e-4126-8195-d2e7358c2283.png">

**Comment by uakihir0** [comment]
@Reactor13 @kleruk88 
Thanks for the report.
I will investigate, do you use `uiPipView.startPictureInPicture(withRefreshInterval: )` to start PiP?

**Comment by Reactor13** [comment]
> @Reactor13 @kleruk88 Thanks for the report. I will investigate, do you use `uiPipView.startPictureInPicture(withRefreshInterval: )` to start PiP?

We have tried both modes. It doesn't affect. CPU usage increases in any case immediately after the appearance of the PIP window itself and even if it is not updated / rendered afterwards.

**Comment by Andrew5** [comment]
How do I control the display size of picture in picture and display it on
the interface with my camera？Object-C代码

Reactor13 ***@***.***> 于2022年12月18日周日 04:49写道：

**Comment by Reactor13** [comment]
Any updates? News?

**Comment by Reactor13** [comment]
iOS 16.3 
problem still exists

**Comment by Reactor13** [comment]
Just downloaded and ran the example from this project. All the same. After clicking Toogle PIP, the processor is loaded at 100%

Xcode 14.2, iOS 16.3, iPhone 14 Pro

**Comment by Reactor13** [comment]
<img width="323" alt="Снимок экрана 2023-02-06 в 14 54 26" src="https://user-images.githubusercontent.com/7979883/216989980-d7a388b1-73d6-46f7-8154-6bc46bde429c.png">

**Comment by Reactor13** [comment]
<img width="384" alt="Снимок экрана 2023-02-06 в 14 57 20" src="https://user-images.githubusercontent.com/7979883/216990517-c0255320-ceb5-46dc-83ca-b83b310f89cb.png">

**Comment by uakihir0** [comment]
Looking at the Profiler, CPU usage is not that much, but this is only the usage of the application, and when we look at the usage of the iPhone as a whole, it becomes a reasonably large usage rate as you have described. Below are the results from the Profiler, focused on PiP usage.

<img width="750" alt="スクリーンショット 2023-02-08 18 51 18" src="https://user-images.githubusercontent.com/1501888/217495531-618253d1-f542-4306-b48b-a53ce5e9c797.png">

On the other hand, when we look at the percentage of time elapsed in the application, the percentage of CPU usage is less than half of the problematic points, which means that the usage is not nearly as problematic as it could be. From this point of view, it seems likely that the cause is a change in the usage of threads per timer due to the OS version upgrade.

<img width="754" alt="スクリーンショット 2023-02-08 18 48 54" src="https://user-images.githubusercontent.com/1501888/217496680-d97b58c6-b120-49c4-9ca5-921412c52427.png">

**Comment by uakihir0** [comment]
If the code is modified not to render, TimeProfiler looks like the following, and the status remains the same. From this point of view, I think there is a problem in the usage of `AVPictureInPictureController` or it is a bug in the OS. I will investigate further.

<img width="619" alt="スクリーンショット 2023-02-08 19 05 51" src="https://user-images.githubusercontent.com/1501888/217499559-0f6f2e13-368b-4343-9dfe-fe1c2778a325.png">

**Comment by uakihir0** [comment]
I have found that AVKit is consuming time during PiP, but I don't know how to control this.

<img width="851" alt="スクリーンショット 2023-02-09 1 02 50" src="https://user-images.githubusercontent.com/1501888/217584288-ef6fea1b-10a0-4b56-81dc-65e7d953015e.png">

**Comment by Reactor13** [comment]
@uakihir0 thank you for answer and investigation report.

**Comment by uakihir0** [comment]
Posted in forum.
https://developer.apple.com/forums/thread/724632

**Comment by eximpression** [comment]
From you post image we can see that the cpu time usage is conern with play timer, so I wondering that maybe CMTimeRange(start: .negativeInfinity, duration: .positiveInfinity) is the problem, so I change this line to  CMTimeRange(start: .zero, duration: .positiveInfinity).
guess what, the cpu usage is drop to 0!
so 
func pictureInPictureControllerTimeRangeForPlayback(_ pictureInPictureController: AVPictureInPictureController) -> CMTimeRange {
        CMTimeRange(start: .negativeInfinity, duration: .positiveInfinity)
    }

is the problem. don't return  negativeInfinity, just zero.

> Posted in forum. https://developer.apple.com/forums/thread/724632

**Comment by eximpression** [comment]
> Posted in forum. https://developer.apple.com/forums/thread/724632

From your post image we can see that the cpu time usage is conern with play timer, so I wondering that maybe CMTimeRange(start: .negativeInfinity, duration: .positiveInfinity) is the problem, so I change this line to  CMTimeRange(start: .zero, duration: CMTimeMake(value: 3600*24, timescale: 1)).
guess what, the cpu usage is drop to 0!
so 
func pictureInPictureControllerTimeRangeForPlayback(_ pictureInPictureController: AVPictureInPictureController) -> CMTimeRange {
        CMTimeRange(start: .negativeInfinity, duration: .positiveInfinity)
    }

is the problem. don't return  negativeInfinity and positiveInfinity, just a finity value it is!

**Comment by uakihir0** [comment]
@eximpression 
Thank you, I have confirmed that the CPU usage will go down.

Fixed in https://github.com/uakihir0/UIPiPView/pull/18.

**Comment by Reactor13** [comment]
🔥 Thank you!
