### ISSUE TITLE
not working with WebRTC

### ISSUE THREAD

**Issue by fukemy** [uakihir0/UIPiPView#2]
hi, thanks for great library, im using your lib when calling(using WebRTC), but it's only display white screen, can u help my problem? Thanks

**Comment by fukemy** [comment]
after check i saw the method toUIImage() return empty 
 open func makeNextVieoBuffer() -> CMSampleBuffer? {
        let image = self.toUIImage() -> can not capture view as UIImage
}

**Comment by fukemy** [comment]
![Ảnh chụp Màn hình 2022-03-16 lúc 17 43 41](https://user-images.githubusercontent.com/8202437/158572604-885867e8-7200-4a52-9548-96f48cb8609a.png)
here is the image i  captured from debug, the video can not captured

**Comment by uakihir0** [comment]
If you want to do PiP with WebRTC, I think it is more reliable to use that method to achieve PiP than to go through UIView, because you can get video resources directly.

**Comment by Andrew5** [comment]
> PiP 
I would like to ask if there is any change PIP window size in OC language?

**Comment by Andrew5** [comment]
How to modify the size of PIP window? I use OC language. Can I have an OC version that can modify the size of PIP window? I'm currently studying. Thank you

**Comment by Andrew5** [comment]
> 如果您想使用WebRTC进行PiP，我认为使用这种方法实现PiP比通过UIView更可靠，因为您可以直接获取视频资源。
