### ISSUE TITLE
[Question] Using Picture In Picture not for video playback

### ISSUE THREAD

**Issue by alex-swiftify** [uakihir0/UIPiPView#23]
Thank you for the awesome library!

As far as I understand, Apple supports Picture in Picture in the following scenarios:
1. For video content playback
2. For video calls

Did anyone succeeded in using the picture-in-picture mode for anything except video playback for App Store apps?

**Comment by uakihir0** [comment]
Hi.

Several apps, including a memo app, can be found in the App Store. 
I don't think they will be rejected unless there is a direct disadvantage to the user. 
Also, of course, the PiP in this library may not be available in future iOS updates.

**Comment by alex-swiftify** [comment]
@uakihir0 Understood, thank you for the samples!
I have a rather unique idea (displaying the screen translation in a PIP window) and evaluating the probability if such a use will be accepted. We’ll see.
