### ISSUE TITLE
Change PIP window size

### ISSUE THREAD

**Issue by Andrew5** [uakihir0/UIPiPView#5]
How to modify the size of PIP window? I use OC language. Can I have an OC version that can modify the size of PIP window? I'm currently studying. Thank you

**Comment by uakihir0** [comment]
Hi.
It is possible to call this Swift library from Objective-C code.
The PiP size corresponds to the size of the UIPiPView. If the UIPiPView is large, iOS will automatically adjust the PiP size. If you pinch in the PiP, the size of the PiP will be reduced.
